# Generated by Django 6.0.1 on 2026-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.CharField(help_text='Gate code (e.g. SOL, PRX)', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('connections', models.JSONField(default=list, help_text='List of outgoing connections with HU distance')),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
                'db_table': 'gate',
            },
        ),
    ]
