
# Transport costs
PERSONAL_TRANSPORT_COST_PER_AU = 0.30
PERSONAL_TRANSPORT_PARKING_PER_DAY = 5.00
PERSONAL_TRANSPORT_MAX_PASSENGERS = 4

HSTC_TRANSPORT_COST_PER_AU = 0.45
HSTC_TRANSPORT_MAX_PASSENGERS = 5

# Hyperspace costs
HYPERSPACE_COST_PER_PASSENGER_PER_HU = 0.10